name: pytest
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
jobs:
  run:
    name: Run unit tests with codecov upload
    runs-on: ${{ matrix.os }}
    env:
      USING_COVERAGE: '3.8'
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10", "3.11"]
    steps:
    - uses: actions/checkout@master

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install --upgrade wheel
        pip3 install pyflakes
        pip3 install -r tests/test_requirements.txt
        pip3 install -e .
    - name: Static code checking with pyflakes
      run: |
        pyflakes mkdocs_enumerate_headings_plugin
    - name: Run unit tests
      run: |
        pytest --cov=mkdocs_enumerate_headings_plugin --cov-report=xml -vvv
    - name: Upload coverage to Codecov
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
